# Traffic flow forecast

In [1]:
import pandas as pd

In [11]:

data_loc = r"~/Desktop/Data Playground/Traffic Flow Forecasting and Analysis"
data_name="traffic_sensor_data.csv"
df = pd.read_csv(f"{data_loc}/{data_name}")

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 218400 entries, 0 to 218399
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   timestamp          218400 non-null  str
 1   sensor_id          218400 non-null  str
 2   location           218400 non-null  str
 3   direction          218400 non-null  str
 4   vehicle_count      218400 non-null  int64
 5   average_speed_kmh  218400 non-null  float64
 6   occupancy_rate     218400 non-null  float64
 7   congestion_level   218400 non-null  str
 8   car_count          218400 non-null  int64
 9   motorcycle_count   218400 non-null  int64
 10  truck_count        218400 non-null  int64
 11  bus_count          218400 non-null  int64
 12  day_of_week        218400 non-null  int64
 13  is_holiday         218400 non-null  int64
 14  hour               218400 non-null  int64
dtypes: float64(2), int64(8), str(5)
memory usage: 25.0 MB

In [13]:
df.head()

,timestamp,sensor_id,location,direction,vehicle_count,average_speed_kmh,occupancy_rate,congestion_level,car_count,motorcycle_count,truck_count,bus_count,day_of_week,is_holiday,hour
0,2024-01-01 00:00:00,SEN-001,Jl. Sudirman - Bundaran HI,North,14,67.8,0.073,Low,6,5,1,2,0,1,0
1,2024-01-01 00:00:00,SEN-002,Jl. Thamrin - Monas,South-West,23,66.8,0.075,Low,10,8,1,4,0,1,0
2,2024-01-01 00:00:00,SEN-003,Jl. Gatot Subroto - Kuningan,East,22,80.0,0.161,Low,7,9,1,5,0,1,0
3,2024-01-01 00:00:00,SEN-004,Jl. Rasuna Said - Setiabudi,East,8,80.0,0.055,Low,3,2,0,3,0,1,0
4,2024-01-01 00:00:00,SEN-005,Jl. HR Rasuna Said - Casablanca,East,13,80.0,0.097,Low,5,5,0,3,0,1,0

In [14]:
df["sensor_id"].unique()

<StringArray>
['SEN-001', 'SEN-002', 'SEN-003', 'SEN-004', 'SEN-005', 'SEN-006', 'SEN-007',
 'SEN-008', 'SEN-009', 'SEN-010', 'SEN-011', 'SEN-012', 'SEN-013', 'SEN-014',
 'SEN-015', 'SEN-016', 'SEN-017', 'SEN-018', 'SEN-019', 'SEN-020', 'SEN-021',
 'SEN-022', 'SEN-023', 'SEN-024', 'SEN-025', 'SEN-026', 'SEN-027', 'SEN-028',
 'SEN-029', 'SEN-030', 'SEN-031', 'SEN-032', 'SEN-033', 'SEN-034', 'SEN-035',
 'SEN-036', 'SEN-037', 'SEN-038', 'SEN-039', 'SEN-040', 'SEN-041', 'SEN-042',
 'SEN-043', 'SEN-044', 'SEN-045', 'SEN-046', 'SEN-047', 'SEN-048', 'SEN-049',
 'SEN-050']
Length: 50, dtype: str

In [18]:
df[df['sensor_id'] == 'SEN-002']

,sensor_id,location,direction,vehicle_count,average_speed_kmh,occupancy_rate,congestion_level,car_count,motorcycle_count,truck_count,bus_count,day_of_week,is_holiday,hour
timestamp,,,,,,,,,,,,,,
2024-01-01 00:00:00,SEN-002,Jl. Thamrin - Monas,South-West,23,66.8,0.075,Low,10,8,1,4,0,1,0
2024-01-01 00:30:00,SEN-002,Jl. Thamrin - Monas,South,28,80.0,0.183,Low,10,9,2,7,0,1,0
2024-01-01 01:00:00,SEN-002,Jl. Thamrin - Monas,South-West,24,80.0,0.154,Low,9,10,2,3,0,1,1
2024-01-01 01:30:00,SEN-002,Jl. Thamrin - Monas,South,28,80.0,0.176,Low,11,11,2,4,0,1,1
2024-01-01 02:00:00,SEN-002,Jl. Thamrin - Monas,South-West,11,80.0,0.083,Low,5,4,0,2,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-31 21:30:00,SEN-002,Jl. Thamrin - Monas,South,23,80.0,0.087,Low,8,8,1,6,6,1,21
2024-03-31 22:00:00,SEN-002,Jl. Thamrin - Monas,North-East,21,80.0,0.110,Low,9,8,1,3,6,1,22
2024-03-31 22:30:00,SEN-002,Jl. Thamrin - Monas,South-West,27,80.0,0.072,Low,13,9,2,3,6,1,22
2024-03-31 23:00:00,SEN-002,Jl. Thamrin - Monas,South-West,8,80.0,0.050,Low,3,2,0,3,6,1,23
2024-03-31 23:30:00,SEN-002,Jl. Thamrin - Monas,North-East,16,80.0,0.147,Low,7,5,0,4,6,1,23

In [19]:
def feature_engineering(df):
    # Convert timestamp to datetime
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # Extract date and time features
    df['year'] = df['timestamp'].dt.year
    df['month'] = df['timestamp'].dt.month
    df['day'] = df['timestamp'].dt.day
    df['hour'] = df['timestamp'].dt.hour
    df['minute'] = df['timestamp'].dt.minute
    df['day_of_week'] = df['timestamp'].dt.dayofweek
    
    
    df.drop(columns=['timestamp','location','direction','car_count','motorcycle_count','truck_count','bus_count'], inplace=True)
    
    return df